# mubox/nbx-data
#
# VERSION               0.1.0

FROM mubox/nbx-base

LABEL name="mubox/nbx-data" version="0.1.0" \
      description="The base for all official Microbox Docker data images. Most users will want to use a different mubox/nbx-* image, which extends this one, in their own projects."

# Install pkgin packages
RUN rm -rf /var/gomicro/db/pkgin && /opt/gomicro/bin/pkgin -y up && \
    /opt/gomicro/bin/pkgin -yV in \
            microinit \
            runit \
        && \
    rm -rf /var/gomicro/db/pkgin/cache

# copy files
COPY scripts/. /var/tmp/

# setup runit
RUN mkdir -p /etc/service
RUN ln -s /etc/service /service

# prepare docker init process
RUN /var/tmp/prepare-docker-init

# Cleanup disk
RUN rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*

WORKDIR /data

# Run runit automatically
CMD ["/opt/gomicro/bin/microinit"]
